### ISSUE TITLE
RENEW YOUR DOMAIN.

### ISSUE THREAD

**Issue by austinhuang0131** [richgieg/runo#1]
THE ONLINE VERSION DOESN'T WORK. SEEMS LIKE YOUR DOMAIN IS TAKEN AWAY BY GODADDY. RENEW IT.

**Comment by austinhuang0131** [comment]
Alright I'm hosting it in http://austinhuang0131.pythonanywhere.com/

**Comment by richgieg** [comment]
Thank you! I was just going to update the README to remove the live link. Do you plan on hosting it there for a while? If so, I'd be very gracious and also happy to point it out in the README.

**Comment by austinhuang0131** [comment]
~~srsly~~

I operate a [Discord server](http://discord.io/0131) (pls join, discord is a nice chat app) and we have event schedule. I am hosting for that.

It's fine if you point it out. Crediting me is optional.

**Comment by richgieg** [comment]
Hmmm... perhaps I will continue hosting it in the near future. I had no idea anyone used it.

**Comment by austinhuang0131** [comment]
Why don't you just use mine for now?

**Comment by richgieg** [comment]
Thanks man! I updated the README.
