### ISSUE TITLE
Allow us to draw a card even if we have a playable card.

### ISSUE THREAD

**Issue by trollbreeder** [richgieg/runo#2]
Please allow us to draw a card even if we do have a playable card.

Its annoying that we have to give up a legendary wild 4 or wild card if we dont have anything else.

**Comment by richgieg** [comment]
Thanks @trollbreeder for pointing this out! I fixed it and will push the changes to GitHub and to the live site shortly.

**Comment by richgieg** [comment]
Changes are live on the site now.
